apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-busybox
  template:
    metadata:
      labels:
        app: dummy-busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sleep", "3600"]
